///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String imagesImagePlaceholder = 'assets/images/image_placeholder.jpeg';

}
